WIP Change kafka to strimzi with oauth

diff --git a/docker-compose/kafka.yaml b/docker-compose/kafka.yaml
--- a/docker-compose/kafka.yaml
+++ b/docker-compose/kafka.yaml
@@ -1,56 +1,60 @@
 version: "2.1"
 
 services:
-  zoo:
-    image: confluentinc/cp-zookeeper:7.2.1
-    hostname: zoo
+  zookeeper:
+    image: quay.io/strimzi/kafka:0.33.2-kafka-3.2.3
+    command:
+      ["sh", "-c", "bin/zookeeper-server-start.sh config/zookeeper.properties"]
     ports:
       - "2181:2181"
     environment:
-      ZOOKEEPER_CLIENT_PORT: 2181
-    mem_limit: 512m
+      LOG_DIR: /tmp/logs
 
+  # kafka:
+  #   image: quay.io/strimzi/kafka:0.33.2-kafka-3.2.3
+  #   command:
+  #     - "sh"
+  #     - "-c"
+  #     - "bin/kafka-server-start.sh /opt/kafka/custom-config/server.config"
+  #   depends_on:
+  #     - zookeeper
+  #   ports:
+  #     - "9092:9092"
+  #   environment:
+  #     LOG_DIR: "/tmp/logs"
+  #   volumes:
+  #     - ../config/kafka/server.config:/opt/kafka/custom-config/server.config
+  #   healthcheck:
+  #     test: nc -z kafka 9092 || exit -1
+  #     start_period: 15s
+  #     interval: 5s
+  #     timeout: 10s
+  #     retries: 10
   kafka:
-    image: confluentinc/cp-kafka:7.2.1
-    hostname: kafka
-    mem_limit: 1024m
+    image: quay.io/strimzi/kafka:0.33.2-kafka-3.2.3
+    command:
+      [
+        "sh",
+        "-c",
+        "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}",
+      ]
+    depends_on:
+      - zookeeper
     ports:
       - "9092:9092"
     environment:
-      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
-      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
-      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
-      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
-      KAFKA_BROKER_ID: 1
-      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
-      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
-      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
-      KAFKA_DELETE_TOPIC_ENABLE: "true"
-    depends_on:
-      - zoo
+      LOG_DIR: "/tmp/logs"
+      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
+      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
+      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
+    volumes:
+      - ../config/kafka/server.config:/opt/kafka/custom-config/server.properties
     healthcheck:
-      test: nc -z localhost 9092 || exit -1
+      test: nc -z kafka 9092 || exit -1
       start_period: 15s
       interval: 5s
       timeout: 10s
       retries: 10
-
-  # This "container" is a workaround to pre-create topics
-  kafka-setup:
-    image: confluentinc/cp-kafka:7.2.1
-    hostname: kafka-setup
-    container_name: kafka-setup
-    volumes:
-      - ../config/kafkaconfig.sh:/etc/config/kafkaconfig.sh
-    command: "bash /etc/config/kafkaconfig.sh"
-    depends_on:
-      kafka:
-        condition: service_healthy
-    environment:
-      # The following settings are listed here only to satisfy the image's requirements.
-      # We override the image's `command` anyways, hence this container will not start a broker.
-      KAFKA_BROKER_ID: ignored
-      KAFKA_ZOOKEEPER_CONNECT: ignored
 
   redpanda:
     image: docker.redpanda.com/vectorized/console:v2.1.1
@@ -69,21 +73,6 @@ services:
       schema-registry:
         condition: service_healthy
 
-  # Kafka Prometheus exporter https://github.com/cloudhut/kminion
-  kafka-minion:
-    image: quay.io/cloudhut/kminion:master
-    hostname: kafka-minion
-    container_name: kafka-minion
-    depends_on:
-      kafka:
-        condition: service_healthy
-    ports:
-      - 8088:8080
-    environment:
-      KAFKA_BROKERS: kafka:19092
-    profiles:
-      - donotstart
-
   schema-registry:
     mem_limit: 256m
     image: confluentinc/cp-schema-registry:7.3.0
@@ -96,7 +85,7 @@ services:
       - "8081:8081"
     environment:
       SCHEMA_REGISTRY_HOST_NAME: schema-registry
-      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:19092"
+      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:9092"
       SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
     healthcheck:
       test: nc -z localhost 8081 || exit -1
@@ -105,6 +94,44 @@ services:
       timeout: 10s
       retries: 10
 
+  kafka-producer-testdata:
+    image: quay.io/strimzi/kafka:0.33.2-kafka-3.2.3
+    entrypoint: /bin/bash
+    command:
+      - -c
+      - |-
+        template=device%s:'{"deviceId":"%s","timestamp":"%s","value":%d}\n'
+        while [ true ]; do
+          echo "Inserted message"
+          counter=$((($$RANDOM % 20) + 1))
+          json_string=$(printf "$$template" "$$counter" "$$counter" "$(date -Ins)" $$RANDOM)
+          echo $$json_string | bin/kafka-console-producer.sh /opt/kafka/custom-config/zookeeper.config --topic $$TOPIC_NAME --bootstrap-server kafka:9092 --property value.serializer=custom.class.serialization.JsonSerializer --property parse.key=true --property key.separator=:
+          ((COUNTER++))
+        done
+    restart: on-failure
+    profiles:
+      - bootstrap
+      - e2e
+    environment:
+      # How much data to generate
+      COUNTER: 0
+      COUNTER_STOP: 3
+      # Input
+      TOPIC_NAME: "JobNameInputTopic"
+      # The following settings are listed here only to satisfy the image's requirements.
+      # We override the image's `command` anyways, hence this container will not start a broker.
+      KAFKA_BROKER_ID: ignored
+      KAFKA_ZOOKEEPER_CONNECT: ignored
+      KAFKA_OAUTH_JWKS_ENDPOINT_URI: http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
+      KAFKA_OAUTH_CLIENT_ID: test
+      KAFKA_OAUTH_CLIENT_SECRET: BQvvCOLUlbWTmpbYSib5cCgIqRXnd71G
+      KAFKA_OAUTH_TOKEN_ENDPOINT_URI: http://keycloak:8080/auth/realms/master/protocol/openid-connect/token
+      KAFKA_SASL_MECHANISMS: OAUTHBEARER
+      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
+    volumes:
+      - ../config/kafka/server.config:/opt/kafka/custom-config/server.config
+
 networks:
   default:
     name: "cheetah-infrastructure"
+    external: true
